language: cpp
sudo: required
dist: bionic
compiler:
  - gcc
  - clang
os:
  - linux
addons:
  apt:
    packages:
    - libboost-dev
    - libboost-program-options-dev
    - libboost-system-dev
    - libboost-test-dev
    - libc-ares-dev
    - libcurl4-openssl-dev
    - libgd-dev
    - libgoogle-perftools-dev
    - libprotobuf-dev
    - libprotoc-dev
    - protobuf-compiler
    - zlib1g-dev
env:
  - BUILD_TYPE=debug
  - BUILD_TYPE=release
script:
  - g++ -v
  - clang++ -v
  - ./build.sh
